---
abstract: 'Simple message queue using PostgreSQL'
author:
  - 'FUJIWARA Shunichiro <fujiwara@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Queue-Q4Pg-Lite
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  DBI: 0
  Filter::Util::Call: 0
  SQL::Abstract: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
